### ISSUE TITLE
"Data Error"

### ISSUE THREAD

**Issue by wangyongqi7** [banqinghe/doraemon#1]
Why my webpage  only show  "Data Error"?

**Comment by banqinghe** [comment]
设计成了图片链接数据需要靠本地上传，防止盗版 = =，但是这个 repo 写了一点点搞别的去了，荒废了，可能明年能写好（不会真有人拉下来跑一下吧🙃

**Comment by wangyongqi7** [comment]
闲来无事探索下，顺便看看Front-End Engineer 的日常🤠
